name: github pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x

      - name: Pin
        run: opam pin -n .

      - name: Depext
        run: opam depext -yt redis redis-sync redis-lwt

      - name: Deps
        run: opam install -d . --deps-only

      - name: Build
        run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: .
          enable_jekyll: true
