name: Build redis
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        ocaml-compiler:
          - 4.03.x
          - 4.10.x
          - 4.12.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam pin -n .
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - name: Install docker compose
      run: sudo pip install docker-compose
      if: ${{ matrix.os == 'ubuntu-latest'}}
    - name: Start containers
      run: docker-compose up -d
      if: ${{ matrix.os == 'ubuntu-latest'}}
    - run: OCAML_REDIS_TEST_SOCKET=$PWD/socket/redis.sock opam exec -- dune runtest
      if: ${{ matrix.os == 'ubuntu-latest'}}
    - name: Stop containers
      run: docker-compose down
      if: ${{ matrix.os == 'ubuntu-latest'}}
